{
 "title": "Intel iGPU",
 "tags": [
  "igpu",
  "intel",
  "transcoding"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Render 3D",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "igpu_engines_render_3d_busy", "legendFormat": "{{__name__}}" },
    { "expr": "igpu_engines_render_3d_sema", "legendFormat": "{{__name__}}" },
    { "expr": "igpu_engines_render_3d_wait", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Blitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "igpu_engines_blitter_busy", "legendFormat": "{{__name__}}" },
    { "expr": "igpu_engines_blitter_sema", "legendFormat": "{{__name__}}" },
    { "expr": "igpu_engines_blitter_wait", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Video",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "igpu_engines_video_busy", "legendFormat": "{{__name__}}" },
    { "expr": "igpu_engines_video_sema", "legendFormat": "{{__name__}}" },
    { "expr": "igpu_engines_video_wait", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Video enhance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "igpu_engines_video_enhance_busy",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "igpu_engines_video_enhance_sema",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "igpu_engines_video_enhance_wait",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    { "expr": "igpu_frequency_actual", "legendFormat": "{{__name__}}" },
    { "expr": "igpu_frequency_requested", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Bandwith",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    { "expr": "igpu_imc_bandwidth_reads", "legendFormat": "{{__name__}}" },
    { "expr": "igpu_imc_bandwidth_writes", "legendFormat": "{{__name__}}" }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "iGPU Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "igpu_power_package", "legendFormat": "{{__name__}}" },
    { "expr": "igpu_power_gpu", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "R6 & Interrupts ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "igpu_rc6", "legendFormat": "{{__name__}}" },
    { "expr": "igpu_interrupts", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Period",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "igpu_period", "legendFormat": "__auto" }
   ]
  }
 ]
}